## Business Problem
Swiggy processes millions of food-delivery journeys across hundreds of cities every month. Accurate Estimated Time of Arrival (ETA) at order placement and during delivery is core to the customer experience — it affects conversion, cancellations, ratings, and retention. Today’s ETA accuracy suffers from many sources of uncertainty: highly variable traffic patterns, weather events, restaurant preparation variability, rider behaviour and skill, order batching/multiple deliveries, and city-specific operational constraints. Inaccurate ETAs cause:
* Reduced customer trust and lower repeat orders.
* Increased cancellations and refund costs.
* Higher support volume and operational interventions.
* Sub-optimal rider allocation and increased rider idle or overtime costs.

## Problem Statement
Swiggy’s objective is to predict the delivery time (minutes) per order at the moment of order placement (and update it dynamically), with business-grade accuracy and uncertainty estimates so the platform can
 (a) show reliable ETAs to customers
 (b) optimize rider allocation.
Build a production-ready, scalable Machine Learning system that predicts per-order delivery time (in minutes) using real-time and historical features (order, rider, restaurant, geospatial, traffic, weather, and temporal signals).

## Dataset Overview
* Rider_id:- Unique identifier for each delivery partner.
* Age       :- Age of the delivery partner.
* Ratings                :-  Average customer rating of the rider.
* vehicle_condition:-Condition of the rider’s vehicle.(0 => poor ,1=>Average, 2=>Good)
* Type_of_vehicle   :-Vehicle used for delivery (motorcycle, scooter, etc.).
* Type_of_order      :-Type of food ordered (snack, meal, drinks, buffet).
* multiple_deliveries:-Number of deliveries assigned to the rider in a single trip.
* pickup_time_minutes:-Time taken by the restaurant to prepare the order.
* restaurant_longitude:-Geographic coordinates of the restaurant.
* delivery_longitude:- Geographic coordinates of the customer’s delivery location.
* Is_weekend             :-Indicates whether the order was placed on a weekend.
* Order_time_hour    :-Hour when the order was placed (0–23).
* order_time_of_day:- Time bucket (morning, afternoon, evening, night).
* Weather                   :-Weather condition during delivery (sunny, cloudy, fog, stormy, sandstorms).
* Traffic                      :-Traffic condition during delivery.
* Festival                    :-Indicates whether the order was placed on a festival day.
* City_type                 :-Classification of city (urban, metropolitan).
* City_name               :-Name/code of the city (BANG, HYD, CHEN, etc.).
* Time_taken              :- Actual time taken (in minutes) to complete the delivery.
* Distance                   :-Distance (in km) between restaurant and delivery location.
* Order_date               :-Date when the order was placed.
* Order_day                :-Day of the month.
* Order_month           :-Month of the order.
* order_day_of_week:-Day of the week (Monday–Sunday).

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r"C:\Users\PRAVALLIKA\Downloads\swiggy_demographic.csv")
df

,rider_id,age,ratings,restaurant_latitude,restaurant_longitude,delivery_latitude,delivery_longitude,order_date,weather,traffic,...,time_taken,city_name,order_day,order_month,order_day_of_week,is_weekend,pickup_time_minutes,order_time_hour,order_time_of_day,distance
0,INDORES13DEL02,37.0,4.9,22.745049,75.892471,22.765049,75.912471,2022-03-19,sunny,high,...,24,INDO,19,3,saturday,1,15.0,11.0,morning,3.025149
1,BANGRES18DEL02,34.0,4.5,12.913041,77.683237,13.043041,77.813237,2022-03-25,stormy,jam,...,33,BANG,25,3,friday,0,5.0,19.0,evening,20.183530
2,BANGRES19DEL01,23.0,4.4,12.914264,77.678400,12.924264,77.688400,2022-03-19,sandstorms,low,...,26,BANG,19,3,saturday,1,15.0,8.0,morning,1.552758
3,COIMBRES13DEL02,38.0,4.7,11.003669,76.976494,11.053669,77.026494,2022-04-05,sunny,medium,...,21,COIMB,5,4,tuesday,0,10.0,18.0,evening,7.790401
4,CHENRES12DEL01,32.0,4.6,12.972793,80.249982,13.012793,80.289982,2022-03-26,cloudy,high,...,30,CHEN,26,3,saturday,1,15.0,13.0,afternoon,6.210138
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45497,JAPRES04DEL01,30.0,4.8,26.902328,75.794257,26.912328,75.804257,2022-03-24,windy,high,...,32,JAP,24,3,thursday,0,10.0,11.0,morning,1.489846
45498,AGRRES16DEL01,21.0,4.6,NaN,NaN,NaN,NaN,2022-02-16,windy,jam,...,36,AGR,16,2,wednesday,0,15.0,19.0,evening,NaN
45499,CHENRES08DEL03,30.0,4.9,13.022394,80.242439,13.052394,80.272439,2022-03-11,cloudy,low,...,16,CHEN,11,3,friday,0,15.0,23.0,night,4.657195
45500,COIMBRES11DEL01,20.0,4.7,11.001753,76.986241,11.041753,77.026241,2022-03-07,cloudy,high,...,26,COIMB,7,3,monday,0,5.0,13.0,afternoon,6.232393
45501,RANCHIRES09DEL02,23.0,4.9,23.351058,85.325731,23.431058,85.405731,2022-03-02,fog,medium,...,36,RANCHI,2,3,wednesday,0,5.0,17.0,evening,12.074396

In [3]:
df.duplicated().sum()

np.int64(0)

In [4]:
df.columns

Index(['rider_id', 'age', 'ratings', 'restaurant_latitude',
       'restaurant_longitude', 'delivery_latitude', 'delivery_longitude',
       'order_date', 'weather', 'traffic', 'vehicle_condition',
       'type_of_order', 'type_of_vehicle', 'multiple_deliveries', 'festival',
       'city_type', 'time_taken', 'city_name', 'order_day', 'order_month',
       'order_day_of_week', 'is_weekend', 'pickup_time_minutes',
       'order_time_hour', 'order_time_of_day', 'distance'],
      dtype='str')

In [5]:
numerical=['age','ratings','vehicle_condition','multiple_deliveries','order_day','order_month','is_weekend',
           'pickup_time_minutes','order_time_hour','distance']

# Dropping irrelevant columns

In [6]:
import warnings
warnings.filterwarnings("ignore")

In [7]:
df.columns

Index(['rider_id', 'age', 'ratings', 'restaurant_latitude',
       'restaurant_longitude', 'delivery_latitude', 'delivery_longitude',
       'order_date', 'weather', 'traffic', 'vehicle_condition',
       'type_of_order', 'type_of_vehicle', 'multiple_deliveries', 'festival',
       'city_type', 'time_taken', 'city_name', 'order_day', 'order_month',
       'order_day_of_week', 'is_weekend', 'pickup_time_minutes',
       'order_time_hour', 'order_time_of_day', 'distance'],
      dtype='str')

In [8]:
df = df.drop(columns=['rider_id', 'order_date', 'restaurant_latitude', 'restaurant_longitude', 'delivery_latitude', 'delivery_longitude'])

In [9]:
x=df.drop(columns=['time_taken'])
y=df['time_taken']

In [10]:
x.head(5)

,age,ratings,weather,traffic,vehicle_condition,type_of_order,type_of_vehicle,multiple_deliveries,festival,city_type,city_name,order_day,order_month,order_day_of_week,is_weekend,pickup_time_minutes,order_time_hour,order_time_of_day,distance
0,37.0,4.9,sunny,high,2,snack,motorcycle,0.0,no,urban,INDO,19,3,saturday,1,15.0,11.0,morning,3.025149
1,34.0,4.5,stormy,jam,2,snack,scooter,1.0,no,metropolitian,BANG,25,3,friday,0,5.0,19.0,evening,20.183530
2,23.0,4.4,sandstorms,low,0,drinks,motorcycle,1.0,no,urban,BANG,19,3,saturday,1,15.0,8.0,morning,1.552758
3,38.0,4.7,sunny,medium,0,buffet,motorcycle,1.0,no,metropolitian,COIMB,5,4,tuesday,0,10.0,18.0,evening,7.790401
4,32.0,4.6,cloudy,high,1,snack,scooter,1.0,no,metropolitian,CHEN,26,3,saturday,1,15.0,13.0,afternoon,6.210138

In [11]:
x.columns

Index(['age', 'ratings', 'weather', 'traffic', 'vehicle_condition',
       'type_of_order', 'type_of_vehicle', 'multiple_deliveries', 'festival',
       'city_type', 'city_name', 'order_day', 'order_month',
       'order_day_of_week', 'is_weekend', 'pickup_time_minutes',
       'order_time_hour', 'order_time_of_day', 'distance'],
      dtype='str')

In [12]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
age,43648.0,29.555008,5.761482,20.000000,25.000000,30.000000,35.00000,39.000000
ratings,43594.0,4.635287,0.313827,2.500000,4.500000,4.700000,4.90000,5.000000
vehicle_condition,45502.0,1.019406,0.835229,0.000000,0.000000,1.000000,2.00000,3.000000
multiple_deliveries,44509.0,0.744928,0.572488,0.000000,0.000000,1.000000,1.00000,3.000000
time_taken,45502.0,26.297591,9.386419,10.000000,19.000000,26.000000,32.00000,54.000000
order_day,45502.0,13.811657,8.709540,1.000000,6.000000,13.000000,20.00000,31.000000
order_month,45502.0,2.980726,0.546031,2.000000,3.000000,3.000000,3.00000,4.000000
is_weekend,45502.0,0.274867,0.446452,0.000000,0.000000,0.000000,1.00000,1.000000
pickup_time_minutes,43862.0,9.989399,4.087516,5.000000,5.000000,10.000000,15.00000,15.000000
order_time_hour,43862.0,17.423966,4.817856,0.000000,15.000000,19.000000,21.00000,23.000000
distance,41872.0,9.719296,5.602890,1.465067,4.657655,9.193014,13.68092,20.969489

In [13]:
df.head()

,age,ratings,weather,traffic,vehicle_condition,type_of_order,type_of_vehicle,multiple_deliveries,festival,city_type,time_taken,city_name,order_day,order_month,order_day_of_week,is_weekend,pickup_time_minutes,order_time_hour,order_time_of_day,distance
0,37.0,4.9,sunny,high,2,snack,motorcycle,0.0,no,urban,24,INDO,19,3,saturday,1,15.0,11.0,morning,3.025149
1,34.0,4.5,stormy,jam,2,snack,scooter,1.0,no,metropolitian,33,BANG,25,3,friday,0,5.0,19.0,evening,20.183530
2,23.0,4.4,sandstorms,low,0,drinks,motorcycle,1.0,no,urban,26,BANG,19,3,saturday,1,15.0,8.0,morning,1.552758
3,38.0,4.7,sunny,medium,0,buffet,motorcycle,1.0,no,metropolitian,21,COIMB,5,4,tuesday,0,10.0,18.0,evening,7.790401
4,32.0,4.6,cloudy,high,1,snack,scooter,1.0,no,metropolitian,30,CHEN,26,3,saturday,1,15.0,13.0,afternoon,6.210138

# DATA PREPROCESSING

## 1)Handling missing values

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45502 entries, 0 to 45501
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   age                  43648 non-null  float64
 1   ratings              43594 non-null  float64
 2   weather              44977 non-null  str
 3   traffic              44992 non-null  str
 4   vehicle_condition    45502 non-null  int64
 5   type_of_order        45502 non-null  str
 6   type_of_vehicle      45502 non-null  str
 7   multiple_deliveries  44509 non-null  float64
 8   festival             45274 non-null  str
 9   city_type            44304 non-null  str
 10  time_taken           45502 non-null  int64
 11  city_name            45502 non-null  str
 12  order_day            45502 non-null  int64
 13  order_month          45502 non-null  int64
 14  order_day_of_week    45502 non-null  str
 15  is_weekend           45502 non-null  int64
 16  pickup_time_minutes  43862 non-null  float64
 17  order_time_hour      43862 non-null  float64
 18  order_time_of_day    45502 non-null  str
 19  distance             41872 non-null  float64
dtypes: float64(6), int64(5), str(9)
memory usage: 6.9 MB

In [15]:
df.isna().sum()

age                    1854
ratings                1908
weather                 525
traffic                 510
vehicle_condition         0
type_of_order             0
type_of_vehicle           0
multiple_deliveries     993
festival                228
city_type              1198
time_taken                0
city_name                 0
order_day                 0
order_month               0
order_day_of_week         0
is_weekend                0
pickup_time_minutes    1640
order_time_hour        1640
order_time_of_day         0
distance               3630
dtype: int64

# Segregating the columns based on datatype

In [16]:
df["weather"].head()

0         sunny
1        stormy
2    sandstorms
3         sunny
4        cloudy
Name: weather, dtype: str

In [17]:
# nominal
nominal=['weather','type_of_order','type_of_vehicle','festival','city_name','order_day_of_week','order_time_of_day']
nominal

['weather',
 'type_of_order',
 'type_of_vehicle',
 'festival',
 'city_name',
 'order_day_of_week',
 'order_time_of_day']

In [18]:
# ordinal
ordinal=['traffic','city_type']
ordinal

['traffic', 'city_type']

In [19]:
df['city_type'].unique()

<StringArray>
['urban', 'metropolitian', 'semi-urban', nan]
Length: 4, dtype: str

In [20]:
order=[["low","medium","high","jam"],['semi-urban','urban','metropolitian']]

In [21]:
# numerical
numerical=['age','ratings','vehicle_condition','multiple_deliveries','order_day','order_month','is_weekend',
           'pickup_time_minutes','order_time_hour','distance']
numerical

['age',
 'ratings',
 'vehicle_condition',
 'multiple_deliveries',
 'order_day',
 'order_month',
 'is_weekend',
 'pickup_time_minutes',
 'order_time_hour',
 'distance']

# Pipeline Creation

In [22]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import StandardScaler

In [23]:
from sklearn.compose import ColumnTransformer

In [24]:
numerical_pipeline=Pipeline([("Numerical impution",SimpleImputer(strategy="median")),
                            ("Feature Scaling",StandardScaler())])
numerical_pipeline

Pipeline(steps=[('Numerical impution', SimpleImputer(strategy='median')),
                ('Feature Scaling', StandardScaler())])

In [25]:
nominal_pipeline=Pipeline([("nominal imputation",SimpleImputer(strategy="most_frequent")),
                          ("Encoding",OneHotEncoder())])
nominal_pipeline

Pipeline(steps=[('nominal imputation', SimpleImputer(strategy='most_frequent')),
                ('Encoding', OneHotEncoder())])

In [26]:
ordinal_pipeline=Pipeline([("Ordinal imputation",SimpleImputer(strategy="most_frequent")),
                          ("Encoding",OrdinalEncoder(categories=order))])
ordinal_pipeline

Pipeline(steps=[('Ordinal imputation', SimpleImputer(strategy='most_frequent')),
                ('Encoding',
                 OrdinalEncoder(categories=[['low', 'medium', 'high', 'jam'],
                                            ['semi-urban', 'urban',
                                             'metropolitian']]))])

In [27]:
Data_preprocessing = ColumnTransformer([
    ('Nominal transformation', nominal_pipeline, nominal),
    ("Ordinal transformation", ordinal_pipeline, ordinal),
    ('Numerical Transformation', numerical_pipeline, numerical)
])

Data_preprocessing

ColumnTransformer(transformers=[('Nominal transformation',
                                 Pipeline(steps=[('nominal imputation',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('Encoding',
                                                  OneHotEncoder())]),
                                 ['weather', 'type_of_order', 'type_of_vehicle',
                                  'festival', 'city_name', 'order_day_of_week',
                                  'order_time_of_day']),
                                ('Ordinal transformation',
                                 Pipeline(steps=[('Ordinal imputation',
                                                  SimpleImpute...
                                                                             ['semi-urban',
                                                                              'urban',
                                                                              'metropolitian']]))]),
                                 ['traffic', 'city_type']),
                                ('Numerical Transformation',
                                 Pipeline(steps=[('Numerical impution',
                                                  SimpleImputer(strategy='median')),
                                                 ('Feature Scaling',
                                                  StandardScaler())]),
                                 ['age', 'ratings', 'vehicle_condition',
                                  'multiple_deliveries', 'order_day',
                                  'order_month', 'is_weekend',
                                  'pickup_time_minutes', 'order_time_hour',
                                  'distance'])])

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=23)

# Model Building

# Linear Regression

In [30]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,root_mean_squared_error,r2_score

In [31]:
lr = Pipeline([
    ('Data Preprocessing', Data_preprocessing),
    ("Algorithm", LinearRegression())
])

lr.fit(x_train, y_train)
y_pred = lr.predict(x_test)
print("mean_squared_error",mean_squared_error(y_test,y_pred))
print("root_mean_squared_error",root_mean_squared_error(y_test,y_pred))
print("R2 score",r2_score(y_test,y_pred))

mean_squared_error 36.94136258193891
root_mean_squared_error 6.07794065304515
R2 score 0.5845096813390458

# KNN

In [32]:
from sklearn.neighbors import KNeighborsRegressor

In [33]:
knn_r=Pipeline([
    ("Data Preprocessing",Data_preprocessing),
    ("Algorithm",KNeighborsRegressor())
])

knn_r.fit(x_train,y_train)
y_pred = knn_r.predict(x_test)
print("mean_squared_error",mean_squared_error(y_test,y_pred))
print("root_mean_squared_error",root_mean_squared_error(y_test,y_pred))
print("R2 score",r2_score(y_test,y_pred))

mean_squared_error 34.29343588616636
root_mean_squared_error 5.85605975773526
R2 score 0.6142916880037183

# Decision Tree Regressor

In [34]:
from sklearn.tree import DecisionTreeRegressor

In [35]:
dt=Pipeline([
    ("Data Preprocessing",Data_preprocessing),
    ("Algorithm",DecisionTreeRegressor())
])

dt.fit(x_train,y_train)
y_pred = dt.predict(x_test)
print("mean_squared_error",mean_squared_error(y_test,y_pred))
print("root_mean_squared_error",root_mean_squared_error(y_test,y_pred))
print("R2 score",r2_score(y_test,y_pred))

mean_squared_error 31.537303593011757
root_mean_squared_error 5.6158083650541135
R2 score 0.6452907146967517

# SVM

In [36]:
from sklearn.svm import SVR

In [37]:
svr = Pipeline([
    ('Data Preprocessing', Data_preprocessing),
    ("Algorithm",SVR())
])

svr.fit(x_train,y_train)
y_pred = svr.predict(x_test)
print("mean_squared_error",mean_squared_error(y_test,y_pred))
print("root_mean_squared_error",root_mean_squared_error(y_test,y_pred))
print("R2_score",r2_score(y_test,y_pred))

mean_squared_error 25.880548012840787
root_mean_squared_error 5.087292798025369
R2_score 0.7089139005870705

# Random Forest Regressor

In [38]:
from sklearn.ensemble import RandomForestRegressor

In [39]:
RandomForestRegressor()

RandomForestRegressor()

In [40]:
rf = Pipeline([
    ('Data Preprocessing', Data_preprocessing),
    ("Algorithm", RandomForestRegressor(random_state=23))
])

rf.fit(x_train,y_train)
y_pred = rf.predict(x_test)
print("mean_squared_error",mean_squared_error(y_test,y_pred))
print("root_mean_squared_error",root_mean_squared_error(y_test,y_pred))
print("r2_score",r2_score(y_test,y_pred))

mean_squared_error 16.9511627293704
root_mean_squared_error 4.117178977087394
r2_score 0.8093453107346065

In [41]:
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

rf.fit(x_train, y_train)


train_pred = rf.predict(x_train)
y_pred = rf.predict(x_test)


train_r2 = r2_score(y_train, train_pred)
test_r2 = r2_score(y_test, y_pred)

print(f"Training R2 Score: {train_r2:.4f}")
print(f"Test R2 Score: {test_r2:.4f}")

Training R2 Score: 0.9728
Test R2 Score: 0.8093

# XGBoost

In [42]:
pip install xgboost

Requirement already satisfied: xgboost in C:\Users\PRAVALLIKA\.conda\envs\mediapipe\Lib\site-packages (3.2.0)
Requirement already satisfied: numpy in C:\Users\PRAVALLIKA\.conda\envs\mediapipe\Lib\site-packages (from xgboost) (2.4.4)
Requirement already satisfied: scipy in C:\Users\PRAVALLIKA\.conda\envs\mediapipe\Lib\site-packages (from xgboost) (1.17.1)
Note: you may need to restart the kernel to use updated packages.

In [43]:
from xgboost import XGBRegressor

In [44]:
xgb = Pipeline([
    ('Data Preprocessing', Data_preprocessing),
    ("Algorithm", XGBRegressor())
])

xgb.fit(x_train,y_train)
y_pred = xgb.predict(x_test)
print("mean_squared_error",mean_squared_error(y_test,y_pred))
print("root_mean_squared_error",root_mean_squared_error(y_test,y_pred))
print("R2 score",r2_score(y_test,y_pred))

mean_squared_error 16.646299362182617
root_mean_squared_error 4.079987525939941
R2 score 0.8127741813659668

In [45]:
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

xgb.fit(x_train, y_train)


train_pred = xgb.predict(x_train)
y_pred = xgb.predict(x_test)

train_r2 = r2_score(y_train, train_pred)
test_r2 = r2_score(y_test, y_pred)

print(f"Training R2 Score: {train_r2:.4f}")
print(f"Test R2 Score: {test_r2:.4f}")

Training R2 Score: 0.8634
Test R2 Score: 0.8128

# kfold-Cross validation

In [46]:
from sklearn.model_selection import KFold,cross_val_score

In [47]:
kfcv=KFold(n_splits=5,shuffle=True,random_state=23)

In [48]:
cross_val_score(estimator=xgb,
               X=x,
               y=y,
               scoring='r2',
               cv=kfcv,
               n_jobs=-1).mean()

np.float64(0.8084364891052246)

# Hyperparamaters

In [49]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    'Algorithm__n_estimators': [100, 200, 300],
    'Algorithm__max_depth': [4, 6, 7, 8],
    'Algorithm__learning_rate': [0.05, 0.1, 0.01],
    }

grid_xgb = GridSearchCV(
    estimator=xgb,
    param_grid=param_grid,
    cv=kfcv,
    scoring='r2',
    n_jobs=-1
)

grid_xgb.fit(x_train, y_train)

print("Best Parameters:", grid_xgb.best_params_)
print("Best CV Score:", grid_xgb.best_score_)

Best Parameters: {'Algorithm__learning_rate': 0.05, 'Algorithm__max_depth': 8, 'Algorithm__n_estimators': 200}
Best CV Score: 0.8157662153244019

# Bayesian Optimization

In [50]:
def Objective(trial):
    # creating  search space
    n_estimators=trial.suggest_int("n_estimators",100,150,200)
    learning_rate=trial.suggest_float("learning_rate",0.01,0.1)
    Algorithm__max_depth=trial.suggest_int("Algorithm__max_depth",6,8)
    Algorithm__subsample=trial.suggest_float("Algorithm__subsample",0.8,1.0)
    
    # Training
    xgb=XGBRegressor(n_estimators=n_estimators,learning_rate=learning_rate,max_depth=Algorithm__max_depth,subsample=Algorithm__subsample)

    trial_pipeline = Pipeline(steps=[
        ('Data Preprocessing', Data_preprocessing), 
        ('Algorithm', xgb)])
    
    #scoring
    score=cross_val_score(trial_pipeline,x,y,scoring="r2",cv=kfcv,n_jobs=-1).mean()
    return score

In [51]:
import optuna

In [52]:
study=optuna.create_study(direction="maximize")

[I 2026-06-03 22:42:05,822] A new study created in memory with name: no-name-0693734f-57e3-4bb8-843d-fea67529ac2d

In [53]:
study.optimize(Objective,n_trials=10)

[I 2026-06-03 22:42:13,368] Trial 0 finished with value: 0.818324065208435 and parameters: {'n_estimators': 100, 'learning_rate': 0.08657899429720124, 'Algorithm__max_depth': 8, 'Algorithm__subsample': 0.8697359859901279}. Best is trial 0 with value: 0.818324065208435.
[I 2026-06-03 22:42:20,482] Trial 1 finished with value: 0.8146021723747253 and parameters: {'n_estimators': 100, 'learning_rate': 0.05325801060485064, 'Algorithm__max_depth': 7, 'Algorithm__subsample': 0.8698508478328404}. Best is trial 0 with value: 0.818324065208435.
[I 2026-06-03 22:42:26,744] Trial 2 finished with value: 0.8175082683563233 and parameters: {'n_estimators': 100, 'learning_rate': 0.04739683089409798, 'Algorithm__max_depth': 8, 'Algorithm__subsample': 0.888474437324614}. Best is trial 0 with value: 0.818324065208435.
[I 2026-06-03 22:42:30,821] Trial 3 finished with value: 0.8167239546775817 and parameters: {'n_estimators': 100, 'learning_rate': 0.07000269834691952, 'Algorithm__max_depth': 7, 'Algorithm__subsample': 0.8936231822578735}. Best is trial 0 with value: 0.818324065208435.
[I 2026-06-03 22:42:35,111] Trial 4 finished with value: 0.8180708765983582 and parameters: {'n_estimators': 100, 'learning_rate': 0.05216878654492308, 'Algorithm__max_depth': 8, 'Algorithm__subsample': 0.9436784050262248}. Best is trial 0 with value: 0.818324065208435.
[I 2026-06-03 22:42:39,561] Trial 5 finished with value: 0.8081155776977539 and parameters: {'n_estimators': 100, 'learning_rate': 0.05646071886641613, 'Algorithm__max_depth': 6, 'Algorithm__subsample': 0.9843581666193815}. Best is trial 0 with value: 0.818324065208435.
[I 2026-06-03 22:42:45,110] Trial 6 finished with value: 0.8168851613998414 and parameters: {'n_estimators': 100, 'learning_rate': 0.07954333682834233, 'Algorithm__max_depth': 7, 'Algorithm__subsample': 0.9068892873807608}. Best is trial 0 with value: 0.818324065208435.
[I 2026-06-03 22:42:49,637] Trial 7 finished with value: 0.8158511281013489 and parameters: {'n_estimators': 100, 'learning_rate': 0.06723783523668825, 'Algorithm__max_depth': 7, 'Algorithm__subsample': 0.9846398463871269}. Best is trial 0 with value: 0.818324065208435.
[I 2026-06-03 22:42:53,509] Trial 8 finished with value: 0.7938040375709534 and parameters: {'n_estimators': 100, 'learning_rate': 0.025824196705091763, 'Algorithm__max_depth': 7, 'Algorithm__subsample': 0.9685788665459786}. Best is trial 0 with value: 0.818324065208435.
[I 2026-06-03 22:42:57,326] Trial 9 finished with value: 0.8183703541755676 and parameters: {'n_estimators': 100, 'learning_rate': 0.05868330405604828, 'Algorithm__max_depth': 8, 'Algorithm__subsample': 0.8045836370772147}. Best is trial 9 with value: 0.8183703541755676.

In [54]:
study.best_params

{'n_estimators': 100,
 'learning_rate': 0.05868330405604828,
 'Algorithm__max_depth': 8,
 'Algorithm__subsample': 0.8045836370772147}

# Final model

In [55]:
from sklearn.metrics import r2_score

In [56]:
# tuned hyperparameters from bayesian optimization 
xgb_model = Pipeline([('Data Preprocessing', Data_preprocessing),
                     ("Algorithm", XGBRegressor(
                         n_estimators=200,
                          learning_rate=0.05,
                          max_depth=8,
                           random_state=23))])


xgb_model.fit(x_train, y_train)
y_pred = xgb_model.predict(x_test)
mse = mean_squared_error(y_test, y_pred)
rmse = root_mean_squared_error(y_test, y_pred)
r2score = r2_score(y_test,y_pred)
print("XGBoost")
print("Mean_Squared_Error:", mse)
print("Root_Mean_Squared_Error:", rmse)
print("R2_Score:",r2score)

XGBoost
Mean_Squared_Error: 15.893646240234375
Root_Mean_Squared_Error: 3.9866836071014404
R2_Score: 0.8212394714355469

In [57]:
final_pipeline = xgb_model.fit(x, y)
final_pipeline

Pipeline(steps=[('Data Preprocessing',
                 ColumnTransformer(transformers=[('Nominal transformation',
                                                  Pipeline(steps=[('nominal '
                                                                   'imputation',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('Encoding',
                                                                   OneHotEncoder())]),
                                                  ['weather', 'type_of_order',
                                                   'type_of_vehicle',
                                                   'festival', 'city_name',
                                                   'order_day_of_week',
                                                   'order_time_of_day']),
                                                 ('Ordinal transformation',
                                                  Pipeline(s...
                              feature_types=None, feature_weights=None,
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=0.05,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=8, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=200, n_jobs=None,
                              num_parallel_tree=None, ...))])

In [58]:
import pickle

In [59]:
with open(r"C:\Users\PRAVALLIKA\Downloads.pkl", "wb") as s:
    pickle.dump(final_pipeline, s)

In [60]:
with open(r"C:\Users\PRAVALLIKA\Downloads.pkl", 'rb') as swiggyproject:
    model = pickle.load(swiggyproject)

In [61]:
import pandas as pd

swiggy_delivery = pd.DataFrame([{'age':25,'ratings': 5,'weather': 'cloudy','traffic': 'jam','vehicle_condition': 1,'type_of_order': 'meal',
                      'type_of_vehicle': 'motorcycle','multiple_deliveries': 3,'festival': 'no','city_type': 'urban','city_name': 'BANG',
                      'order_day': 13,'order_month': 6,'order_day_of_week': 'saturday','is_weekend': 1,'pickup_time_minutes': 10,
                      'order_time_hour': 18,'order_time_of_day': 'evening','distance': 5.5}])
y_pred = final_pipeline.predict(swiggy_delivery)

print("Delivery Time:", y_pred[0])

Delivery Time: 41.263344